add_subdirectory(common)
if(BUILD_COMPONENT_PIPELINE)
    add_subdirectory(types)
    add_subdirectory(ingestion)
    add_subdirectory(order_book)
    add_subdirectory(pricing)
    add_subdirectory(hedging)
endif()
add_subdirectory(main)
add_subdirectory(market)
add_subdirectory(scheduler)
add_subdirectory(trading)
add_subdirectory(results)
add_subdirectory(runtime)
